name: PR Validation

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  pr-title-validation:
    uses: arzian-cd/arzianghanchi/.github/workflows/shared-workflow-pr-title-check.yaml@master
    with:
      regex: '^(Feat:|feat:|Fix:|fix:|Docs:|docs:|Test:|test:|ci:|refactor:|chore:|revert:) '
